package com.aptota.app.model;
// Generated Jun 30, 2019 8:15:08 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QuotationItem generated by hbm2java
 */
@Entity
@Table(name = "quotation_item", catalog = "inventory_manager")
public class QuotationItem implements java.io.Serializable {

	private Integer quotationItemId;
	private Integer quotationRefId;
	private Integer itemRefId;
	private double amount;
	private Integer quantity;

	public QuotationItem() {
	}

	public QuotationItem(Integer quotationRefId, Integer itemRefId, Integer amount) {
		this.quotationRefId = quotationRefId;
		this.itemRefId = itemRefId;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "quotation_item_id", unique = true, nullable = false)
	public Integer getQuotationItemId() {
		return this.quotationItemId;
	}

	public void setQuotationItemId(Integer quotationItemId) {
		this.quotationItemId = quotationItemId;
	}

	@Column(name = "quotation_ref_id")
	public Integer getQuotationRefId() {
		return this.quotationRefId;
	}

	
	public void setQuotationRefId(Integer quotationRefId) {
		this.quotationRefId = quotationRefId;
	}

	@Column(name = "item_ref_id")
	public Integer getItemRefId() {
		return this.itemRefId;
	}

	public void setItemRefId(Integer itemRefId) {
		this.itemRefId = itemRefId;
	}

	@Column(name = "amount")
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	
	
	

}
