package com.aptota.app.model;
// Generated Apr 15, 2019 7:11:09 AM by Hibernate Tools 4.3.5.Final

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *  generated by hbm2java
 */
@Entity
@Table(name = "quotation", catalog = "inventory_manager")
public class Quotation implements java.io.Serializable {

	private Integer quotationId;
	private Date CDate;
	private String CUser;
	private Date MDate;
	private String MUser;
	private String logitude;
	private String latitude;
	private Integer customerRefId;
	private String quatationStatus;
	private Double amount;
	private String quatationType;
	private String salesRef;
	private String marketingManager;
	private String agentName;
	private Date expDeliveryDate;
	private String salesType;

	public Quotation() {
	}

	public Quotation(Date CDate, String CUser, Date MDate, String MUser,
			String logitude, String latitude, Integer customerRefId, String quatationStatus, Double amount,
			String quatationType, String salesRef, String marketingManager, String agentName) {
		this.CDate = CDate;
		this.CUser = CUser;
		this.MDate = MDate;
		this.MUser = MUser;
		this.logitude = logitude;
		this.latitude = latitude;
		this.customerRefId = customerRefId;
		this.quatationStatus = quatationStatus;
		this.amount = amount;
		this.quatationType = quatationType;
		this.salesRef = salesRef;
		this.marketingManager = marketingManager;
		this.agentName = agentName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "quotation_id", unique = true, nullable = false)
	public Integer getQuotationId() {
		return this.quotationId;
	}

	public void setQuotationId(Integer quotationId) {
		this.quotationId = quotationId;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "exp_delivery_date", length = 19)
	public Date getExpDeliveryDate() {
		return this.expDeliveryDate;
	}

	public void setExpDeliveryDate(Date expDeliveryDate) {
		this.expDeliveryDate = expDeliveryDate;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "c_date", length = 19)
	public Date getCDate() {

		Date todayDate = new Date();
		return this.CDate;
	}

	public void setCDate(Date CDate) {
		this.CDate = CDate;
	}

	@Column(name = "c_user", length = 45)
	public String getCUser() {
		return this.CUser;
	}

	public void setCUser(String CUser) {
		this.CUser = CUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "m_date", length = 19)
	public Date getMDate() {
		return this.MDate;
	}

	public void setMDate(Date MDate) {
		this.MDate = MDate;
	}

	@Column(name = "m_user", length = 45)
	public String getMUser() {
		return this.MUser;
	}

	public void setMUser(String MUser) {
		this.MUser = MUser;
	}

	@Column(name = "logitude", length = 45)
	public String getLogitude() {
		return this.logitude;
	}

	public void setLogitude(String logitude) {
		this.logitude = logitude;
	}

	@Column(name = "latitude", length = 45)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

//	@Column(name = "customer_ref_id", length = 10)
//	public Integer getQuatationRefId() {
//		return this.customerRefId;
//	}
//
//	public void setQuatationRefId(Integer customerRefId) {
//		this.customerRefId = customerRefId;
//	}

	@Column(name = "quatation_status", length = 1)
	public String getQuatationStatus() {
		return this.quatationStatus;
	}

	public void setQuatationStatus(String quatationStatus) {
		this.quatationStatus = quatationStatus;
	}

	@Column(name = "amount", length = 45)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "quatation_type", length = 10)
	public String getQuatationType() {
		return this.quatationType;
	}

	public void setQuatationType(String quatationType) {
		this.quatationType = quatationType;
	}

	@Column(name = "sales_ref", length = 45)
	public String getSalesRef() {
		return this.salesRef;
	}

	public void setSalesRef(String salesRef) {
		this.salesRef = salesRef;
	}

	@Column(name = "marketing_manager", length = 45)
	public String getMarketingManager() {
		return this.marketingManager;
	}

	public void setMarketingManager(String marketingManager) {
		this.marketingManager = marketingManager;
	}

	@Column(name = "agent_name", length = 45)
	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	public Integer getCustomerRefId() {
		return customerRefId;
	}

	public void setCustomerRefId(Integer customerRefId) {
		this.customerRefId = customerRefId;
	}
	@Column(name = "sales_type", length = 15)
	public String getSalesType() {
		return salesType;
	}

	public void setSalesType(String salesType) {
		this.salesType = salesType;
	}
	
	
}
