package com.aptota.app.model;
// Generated Mar 26, 2020 3:57:56 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hallbooking generated by hbm2java
 */
@Entity
@Table(name = "hallbooking", catalog = "restaurent_erp")
public class Hallbooking implements java.io.Serializable {

	private Integer idhallbooking;
	private Integer hallId;
	private Date bookingTime;
	private Date bookingDate;
	private Integer numberOfQuests;
	private Double price;
	private Double advancedPaid;
	private Double totalPayment;
	private Date totalPaidDate;

	public Hallbooking() {
	}

	public Hallbooking(Integer hallId, Date bookingTime, Date bookingDate, Integer numberOfQuests, Double price,
			Double advancedPaid, Double totalPayment, Date totalPaidDate) {
		this.hallId = hallId;
		this.bookingTime = bookingTime;
		this.bookingDate = bookingDate;
		this.numberOfQuests = numberOfQuests;
		this.price = price;
		this.advancedPaid = advancedPaid;
		this.totalPayment = totalPayment;
		this.totalPaidDate = totalPaidDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idhallbooking", unique = true, nullable = false)
	public Integer getIdhallbooking() {
		return this.idhallbooking;
	}

	public void setIdhallbooking(Integer idhallbooking) {
		this.idhallbooking = idhallbooking;
	}

	@Column(name = "hall_id")
	public Integer getHallId() {
		return this.hallId;
	}

	public void setHallId(Integer hallId) {
		this.hallId = hallId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "booking_time", length = 19)
	public Date getBookingTime() {
		return this.bookingTime;
	}

	public void setBookingTime(Date bookingTime) {
		this.bookingTime = bookingTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "booking_date", length = 19)
	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	@Column(name = "number_of_quests")
	public Integer getNumberOfQuests() {
		return this.numberOfQuests;
	}

	public void setNumberOfQuests(Integer numberOfQuests) {
		this.numberOfQuests = numberOfQuests;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "advanced_paid", precision = 22, scale = 0)
	public Double getAdvancedPaid() {
		return this.advancedPaid;
	}

	public void setAdvancedPaid(Double advancedPaid) {
		this.advancedPaid = advancedPaid;
	}

	@Column(name = "total_payment", precision = 22, scale = 0)
	public Double getTotalPayment() {
		return this.totalPayment;
	}

	public void setTotalPayment(Double totalPayment) {
		this.totalPayment = totalPayment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "total_paid_date", length = 19)
	public Date getTotalPaidDate() {
		return this.totalPaidDate;
	}

	public void setTotalPaidDate(Date totalPaidDate) {
		this.totalPaidDate = totalPaidDate;
	}

}
