package com.aptota.app.model;
// Generated Mar 26, 2020 3:57:56 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hall generated by hbm2java
 */
@Entity
@Table(name = "hall", catalog = "restaurent_erp")
public class Hall implements java.io.Serializable {

	private Integer idhall;
	private String hallName;
	private String description;
	private String place;
	private String charge;

	public Hall() {
	}

	public Hall(String hallName, String description, String place, String charge) {
		this.hallName = hallName;
		this.description = description;
		this.place = place;
		this.charge = charge;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idhall", unique = true, nullable = false)
	public Integer getIdhall() {
		return this.idhall;
	}

	public void setIdhall(Integer idhall) {
		this.idhall = idhall;
	}

	@Column(name = "hall_name", length = 25)
	public String getHallName() {
		return this.hallName;
	}

	public void setHallName(String hallName) {
		this.hallName = hallName;
	}

	@Column(name = "description", length = 145)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "place", length = 45)
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "charge", length = 45)
	public String getCharge() {
		return this.charge;
	}

	public void setCharge(String charge) {
		this.charge = charge;
	}

}
