package com.aptota.app.model;
// Generated Mar 26, 2020 3:57:56 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", catalog = "restaurent_erp")
public class Item implements java.io.Serializable {

	private Integer iditem;
	private String itemCode;
	private String itemDescription;
	private String itemType;
	private Double totalQuantity;

	public Item() {
	}

	public Item(String itemCode, String itemDescription, String itemType, Double totalQuantity) {
		this.itemCode = itemCode;
		this.itemDescription = itemDescription;
		this.itemType = itemType;
		this.totalQuantity = totalQuantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iditem", unique = true, nullable = false)
	public Integer getIditem() {
		return this.iditem;
	}

	public void setIditem(Integer iditem) {
		this.iditem = iditem;
	}

	@Column(name = "item_code", length = 25)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "item_description")
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "item_type", length = 45)
	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	@Column(name = "total_quantity", precision = 22, scale = 0)
	public Double getTotalQuantity() {
		return this.totalQuantity;
	}

	public void setTotalQuantity(Double totalQuantity) {
		this.totalQuantity = totalQuantity;
	}

}
