package com.aptota.app.model;
// Generated Mar 26, 2020 3:57:56 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemUsage generated by hbm2java
 */
@Entity
@Table(name = "item_usage", catalog = "restaurent_erp")
public class ItemUsage implements java.io.Serializable {

	private ItemUsageId id;
	private Integer orderId;
	private Integer orderItemId;
	private Date usagetime;

	public ItemUsage() {
	}

	public ItemUsage(ItemUsageId id) {
		this.id = id;
	}

	public ItemUsage(ItemUsageId id, Integer orderId, Integer orderItemId, Date usagetime) {
		this.id = id;
		this.orderId = orderId;
		this.orderItemId = orderItemId;
		this.usagetime = usagetime;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idItemUsage", column = @Column(name = "id_item_usage", nullable = false)),
			@AttributeOverride(name = "usage", column = @Column(name = "usage", nullable = false, precision = 22, scale = 0)) })
	public ItemUsageId getId() {
		return this.id;
	}

	public void setId(ItemUsageId id) {
		this.id = id;
	}

	@Column(name = "order_id")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_item_id")
	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "usagetime", length = 19)
	public Date getUsagetime() {
		return this.usagetime;
	}

	public void setUsagetime(Date usagetime) {
		this.usagetime = usagetime;
	}

}
