package com.aptota.app.model;
// Generated Mar 26, 2020 3:57:56 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemUsageId generated by hbm2java
 */
@Embeddable
public class ItemUsageId implements java.io.Serializable {

	private int idItemUsage;
	private double usage;

	public ItemUsageId() {
	}

	public ItemUsageId(int idItemUsage, double usage) {
		this.idItemUsage = idItemUsage;
		this.usage = usage;
	}

	@Column(name = "id_item_usage", nullable = false)
	public int getIdItemUsage() {
		return this.idItemUsage;
	}

	public void setIdItemUsage(int idItemUsage) {
		this.idItemUsage = idItemUsage;
	}

	@Column(name = "usage", nullable = false, precision = 22, scale = 0)
	public double getUsage() {
		return this.usage;
	}

	public void setUsage(double usage) {
		this.usage = usage;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemUsageId))
			return false;
		ItemUsageId castOther = (ItemUsageId) other;

		return (this.getIdItemUsage() == castOther.getIdItemUsage()) && (this.getUsage() == castOther.getUsage());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdItemUsage();
		result = 37 * result + (int) this.getUsage();
		return result;
	}

}
