package com.aptota.app.model;
// Generated Mar 26, 2020 3:57:56 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KitchenItem generated by hbm2java
 */
@Entity
@Table(name = "kitchen_item", catalog = "restaurent_erp")
public class KitchenItem implements java.io.Serializable {

	private Integer idkitchenItem;
	private Integer orderId;
	private Integer orderItemId;
	private Date receviedTime;
	private Date deliveredTime;

	public KitchenItem() {
	}

	public KitchenItem(Integer orderId, Integer orderItemId, Date receviedTime, Date deliveredTime) {
		this.orderId = orderId;
		this.orderItemId = orderItemId;
		this.receviedTime = receviedTime;
		this.deliveredTime = deliveredTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idkitchen_item", unique = true, nullable = false)
	public Integer getIdkitchenItem() {
		return this.idkitchenItem;
	}

	public void setIdkitchenItem(Integer idkitchenItem) {
		this.idkitchenItem = idkitchenItem;
	}

	@Column(name = "order_id")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "order_item_id")
	public Integer getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "recevied_time", length = 19)
	public Date getReceviedTime() {
		return this.receviedTime;
	}

	public void setReceviedTime(Date receviedTime) {
		this.receviedTime = receviedTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Delivered_time", length = 19)
	public Date getDeliveredTime() {
		return this.deliveredTime;
	}

	public void setDeliveredTime(Date deliveredTime) {
		this.deliveredTime = deliveredTime;
	}

}
