package com.aptota.app.model;
// Generated Mar 26, 2020 3:57:56 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name = "purchase", catalog = "restaurent_erp")
public class Purchase implements java.io.Serializable {

	private Integer idpurchase;
	private Integer amount;
	private String grnCode;
	private Date purchaseDate;
	private Integer unitPrice;
	private Integer itemId;
	private Integer supplier;
	private String purchaseBy;
	private String purchaseType;
	private Double quantity;

	public Purchase() {
	}

	public Purchase(Integer amount, String grnCode, Date purchaseDate, Integer unitPrice, Integer itemId,
			Integer supplier, String purchaseBy, String purchaseType, Double quantity) {
		this.amount = amount;
		this.grnCode = grnCode;
		this.purchaseDate = purchaseDate;
		this.unitPrice = unitPrice;
		this.itemId = itemId;
		this.supplier = supplier;
		this.purchaseBy = purchaseBy;
		this.purchaseType = purchaseType;
		this.quantity = quantity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpurchase", unique = true, nullable = false)
	public Integer getIdpurchase() {
		return this.idpurchase;
	}

	public void setIdpurchase(Integer idpurchase) {
		this.idpurchase = idpurchase;
	}

	@Column(name = "amount")
	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	@Column(name = "grn_code", length = 45)
	public String getGrnCode() {
		return this.grnCode;
	}

	public void setGrnCode(String grnCode) {
		this.grnCode = grnCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "purchase_date", length = 19)
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	@Column(name = "unit_price")
	public Integer getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Integer unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "item_id")
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@Column(name = "supplier")
	public Integer getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Integer supplier) {
		this.supplier = supplier;
	}

	@Column(name = "purchase_by", length = 15)
	public String getPurchaseBy() {
		return this.purchaseBy;
	}

	public void setPurchaseBy(String purchaseBy) {
		this.purchaseBy = purchaseBy;
	}

	@Column(name = "purchase_type", length = 10)
	public String getPurchaseType() {
		return this.purchaseType;
	}

	public void setPurchaseType(String purchaseType) {
		this.purchaseType = purchaseType;
	}

	@Column(name = "quantity", precision = 22, scale = 0)
	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

}
