package com.aptota.app.model;
// Generated Mar 26, 2020 3:57:56 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "restaurent_erp")
public class User implements java.io.Serializable {

	private Integer id;
	private String username;
	private String email;
	private String password;
	private boolean enabled;
	private String fname;
	private String lname;
	private String contact;
	private Boolean salesPerson;
	@Transient
	private List<String> userroles;
	public User() {
	}

	public User(String username, String password, boolean enabled) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
	}

	public User(String username, String email, String password, boolean enabled, String fname, String lname,
			String contact, Boolean salesPerson) {
		this.username = username;
		this.email = email;
		this.password = password;
		this.enabled = enabled;
		this.fname = fname;
		this.lname = lname;
		this.contact = contact;
		this.salesPerson = salesPerson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "fname", length = 150)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "lname", length = 150)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "contact", length = 15)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "sales_person")
	public Boolean getSalesPerson() {
		return this.salesPerson;
	}

	public void setSalesPerson(Boolean salesPerson) {
		this.salesPerson = salesPerson;
	}
	@Transient
	public List<String> getUserroles() {
		return userroles;
	}
	public void setUserroles(List<String> userroles) {
		this.userroles = userroles;
	}

}
